config/routes.rb
Rails.application.routes.draw do
  root "hobbies#index"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :hobbies
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hobby.rb
class Hobby < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :hobbies

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :authenticate_user!
  
    protected
      def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
      end
end

app/controllers/hobbies_controller.rb
class HobbiesController < ApplicationController
  before_action :set_hobby, only: [:show, :edit, :update]

  def index
    @hobbies = current_user.hobbies
  end

  def show
  end

  def new
    @hobby = Hobby.new
  end

  def create 
    @hobby = current_user.hobbies.new(hobby_params)
      if @hobby.save
        flash[:success] = "hobby: #{@hobby.name} Created"
        redirect_to hobbies_path
      else
        flash[:error] = "Error #{@hobby.errors.full_messages.join("\n")}"
        render :new
      end
  end

  def edit
  end

  def update
    if @hobby.update(hobby_params)
      redirect_to hobbies_path
    else
      render :edit
    end
  end

  def destroy
    @hobby.destroy
    redirect_to hobbies_path
  end

  private
    def hobby_params
      params.require(:hobby).permit(:name, :balance)
    end

    # don't just find by the hobby model or you may potentially be able to view other users hobbies
    def set_hobby
      @hobby = current_user.hobbies.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hobbies_helper.rb
module HobbiesHelper
end

app/views/hobbies/edit.html.erb
<h1>Hobbies#edit</h1>
<p>Find me in app/views/hobbies/edit.html.erb</p>

app/views/hobbies/index.html.erb
<%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "btn dark blue" %>
<h2>Welcome <%= current_user.full_name %></h2>
<hr />
<%= link_to "Add Hobby", new_hobby_path, class: "btn dark green-3" %>
<h3>Your Hobbies</h3>
<ul>
  <% @hobby.each do |a| %>
    <li>
      <%= a.activity_name %>
    </li>
  <% end %>
</ul>

app/views/hobbies/new.html.erb
<h1>Add Hobby</h1>
<br/>
<%= form_with(model: @hobby, local: true) do |f| %>
  <div class="field">
    <%= f.label :activity_name %>
    <%= f.text_field :activity_name, required: true, placeholder: "Hobby Name" %>
  </div>

  <%= f.submit "Create Hobby", class: "btn light-green accent-3" %>
  <!-- putting nil instead of create taco will give you the default "Create Account" -->
<% end %>

app/views/hobbies/show.html.erb
<h1>Hobbies#show</h1>
<p>Find me in app/views/hobbies/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevisePractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>